version: '3.3'
services:
  cfgsvr1:
    container_name: cfgsvr1
    image: mongo
    command: mongod --configsvr --replSet cfg_SapRs --port 27017 --dbpath /data/db
    ports:
      - 28000:27017
    volumes:
      - cfgsvr1:/data/db
    networks: 
            - default
  cfgsvr2:
    container_name: cfgsvr2
    image: mongo
    command: mongod --configsvr --replSet cfg_SapRs --port 27017 --dbpath /data/db
    ports:
      - 28001:27017
    volumes:
      - cfgsvr2:/data/db
    networks: 
            - default
  cfgsvr3:
    container_name: cfgsvr3
    image: mongo
    command: mongod --configsvr --replSet cfg_SapRs --port 27017 --dbpath /data/db
    ports:
      - 28002:27017
    volumes:
      - cfgsvr3:/data/db
    networks: 
            - default

volumes:
  cfgsvr1: {}
  cfgsvr2: {}
  cfgsvr3: {}

networks: 
    default:
      external:
        name: CCP